#!/usr/bin/env python

import rospy
import tf
from sensor_msgs.msg import Imu
from std_msgs.msg import Float64	

class ImuToRPY():
	def __init__(self):
		rospy.init_node('imu_to_rpy', anonymous=True)
		
		self.pub_roll = rospy.Publisher('/imu_to_rpy/roll', Float64, queue_size=10)
		self.pub_pitch = rospy.Publisher('/imu_to_rpy/pitch', Float64, queue_size=10)
		self.pub_yaw = rospy.Publisher('/imu_to_rpy/yaw', Float64, queue_size=10)
		self.sub_at = rospy.Subscriber("/mavros/imu/data", Imu, self.callback)
	
		rospy.loginfo("Starting Imu to RPY spinner")
	
		rospy.spin()
		
	def callback(self, data):
		q = data.orientation
		(r, p, y) = tf.transformations.euler_from_quaternion([q.x, q.y, q.z, q.w])
		
		self.pub_roll.publish(r)
		self.pub_pitch.publish(p)
		self.pub_yaw.publish(y)

if __name__ == '__main__':
	try:
		spinner = ImuToRPY()
	except rospy.ROSInterruptException:
		pass